spring:
  datasource:
    url: jdbc:mysql://namo-mysql.cgairc22eznz.ap-northeast-2.rds.amazonaws.com:3306/ppurio
    username: ppurio
    password: answkdb!))$
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: false
    properties:
      hibernate:
        format_sql: true

  devtools:
    livereload:
      enabled: true
  thymeleaf:
    cache: false

logging:
  level:
    org:
      hibernate.SQL: debug
      springframework.security: debug
namo:
  enable-ip-protect: false
  nice-site-code: BR867
  nice-site-password: Ic7XMo9rwnHI
